# Generated by Django 6.0.6 on 2026-07-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0002_githubrun_github_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='platform'),
        ),
    ]
